#!/bin/bash
mkfs.ext4 /dev/sda3
mkfs.ext2 /dev/sda1
mkdir /mnt/gentoo
mount /dev/sda3 /mnt/gentoo
mkdir /mnt/gentoo/boot
mount /dev/sda1 /mnt/gentoo/boot
cd /mnt/gentoo/
dt=$(date -d "3 day ago" +%Y%m%d)
wget http://gentoo.mirrors.tds.net/gentoo/releases/amd64/autobuilds/current-stage3-amd64/stage3-amd64-${dt}.tar.bz2
tar xvjpf stage3-*.tar.bz2 --xattrs
cpucores=grep -c ^processor /proc/cpuinfo
echo "MAKEOPTS=\"-j${cpucores}\"" >> /etc/portage/make.conf
echo CFLAGS="-march=native ${CFLAGS}"
echo CXXFLAGS="${CFLAGS}"
cp -L /etc/resolv.conf /mnt/gentoo/etc/
mount -t proc proc /mnt/gentoo/proc
mount --rbind /sys /mnt/gentoo/sys
mount --make-rslave /mnt/gentoo/sys
mount --rbind /dev /mnt/gentoo/dev
mount --make-rslave /mnt/gentoo/dev
cp .config /mnt/gentoo/.kconfig
chmod +x post.sh
cp post.sh /mnt/gentoo/
chroot /mnt/gentoo ./post.sh
